version: '3.4'

services:
  hungphatuniform:
    image: hungphatuniform
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    deploy:
      restart_policy:
        condition: unless-stopped
