import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { SliderTop } from '@components/slider-top'
import styles from '../styles/Home.module.css'
import bfooter from '@assets/images/bfooter.png'
import WithLayout from '@hoc/WithLayout'

const Home: NextPage = () => {
  console.log(bfooter)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full md:w-8/12 mx-auto"></div>
      <div className="layout">
        <SliderTop />
      </div>
      <div
        style={{
          backgroundImage: `url(${bfooter.src})`,
          backgroundRepeat: 'repeat-x',
          backgroundPosition: 'center bottom',
          backgroundSize: 'contain',
        }}
        className="h-[95px] w-full bg-[#f2f2f2]"
      ></div>
    </>
  )
}

export default WithLayout(Home)
